# -*- coding: utf-8 -*-
"""Colab'e hoş geldiniz. adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZDSzuFgDLnHpvZY_4ESnY-yBORt89FI9
"""

!pip install openpyxl -q

import pandas as pd
import numpy as np
import re

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report
from sklearn.utils import resample

df = pd.read_excel("/content/Last_HouseMD_DataSet.xlsx")

print(df.head())

print(df.columns)

df = df.dropna(subset=["text", "Organ"])

df = df.drop_duplicates()

def temizle(text):

    text = str(text).lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"\d+", "", text)

    text = re.sub(r"[^a-zçğıöşü\s]", "", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text

df["text"] = df["text"].apply(temizle)

df = df[df["text"].str.len() > 5]

print(df["Organ"].value_counts())

df_filtered_for_stratify = df[df["Organ"].map(df["Organ"].value_counts()) >= 25]

min_count = df_filtered_for_stratify["Organ"].value_counts().min()

balanced_df = (
    df_filtered_for_stratify.groupby("Organ", group_keys=False)
      .sample(n=min_count, random_state=42)
).reset_index(drop=True)

import random

def random_swap(words, n=1):
    words = list(words)
    if len(words) < 2:
        return ' '.join(words)

    new_words = words[:]
    for _ in range(n):
        idx1, idx2 = random.sample(range(len(new_words)), 2)
        new_words[idx1], new_words[idx2] = new_words[idx2], new_words[idx1]
    return ' '.join(new_words)


augmented_data = []
num_aug_per_sample = 1

for index, row in balanced_df.iterrows():
    original_text = row['text']
    original_organ = row['Organ']

    augmented_data.append({'text': original_text, 'Organ': original_organ})

    words = original_text.split()
    for _ in range(num_aug_per_sample):
        swapped_text = random_swap(words, n=2)
        augmented_data.append({'text': swapped_text, 'Organ': original_organ})

augmented_df = pd.DataFrame(augmented_data)

combined_df = pd.concat([balanced_df, augmented_df]).reset_index(drop=True)

print(f"Original balanced_df size: {len(balanced_df)}")
print(f"Augmented combined_df size: {len(combined_df)}")
print("Example of augmented text:")
print(combined_df[combined_df['text'] != balanced_df['text'].iloc[0]].iloc[0])

!pip install transformers -q

from transformers import pipeline
import random
fill_mask = pipeline(
    "fill-mask",
    model="dbmdz/bert-base-turkish-cased",
    tokenizer="dbmdz/bert-base-turkish-cased",
    device=-1
)

def bert_augment_text(text, num_augmentations=1, mask_percentage=0.15):
    words = text.split()
    augmented_texts = [text]

    if len(words) < 2:
        return augmented_texts

    for _ in range(num_augmentations):
        masked_words = words[:]
        num_to_mask = max(1, int(len(words) * mask_percentage))
        indices_to_mask = random.sample(range(len(words)), num_to_mask)

        for idx in indices_to_mask:
            masked_words[idx] = fill_mask.tokenizer.mask_token

        masked_sentence = " ".join(masked_words)


        try:

            filled_text = masked_sentence
            for _ in range(num_to_mask):
                if fill_mask.tokenizer.mask_token in filled_text:
                    preds = fill_mask(filled_text)
                    mask_index = filled_text.find(fill_mask.tokenizer.mask_token)
                    if preds and isinstance(preds[0], list):
                         best_token = preds[0][0]['token_str']
                    elif preds and isinstance(preds, list) and isinstance(preds[0], dict):
                         best_token = preds[0]['token_str']
                    else:
                        best_token = ""
                    filled_text = filled_text.replace(fill_mask.tokenizer.mask_token, best_token, 1)
                else:
                    break

            augmented_texts.append(filled_text)
        except Exception as e:
            print(f"Error augmenting text: {text}. Error: {e}")
            augmented_texts.append(text)

    return augmented_texts

bert_augmented_data = []
num_bert_aug_per_sample = 1

for index, row in balanced_df.iterrows():
    original_text = row['text']
    original_organ = row['Organ']

    augmented_samples = bert_augment_text(original_text, num_bert_aug_per_sample, mask_percentage=0.2)
    for aug_text in augmented_samples:
        bert_augmented_data.append({'text': aug_text, 'Organ': original_organ})

bert_combined_df = pd.DataFrame(bert_augmented_data)

print(f"Original balanced_df size: {len(balanced_df)}")
print(f"BERT Augmented combined_df size: {len(bert_combined_df)}")
print("Example of BERT augmented text:")
original_example = balanced_df['text'].iloc[0]
augmented_example = bert_combined_df[bert_combined_df['text'] != original_example].iloc[0]
print(f"Original: {original_example}")
print(f"Augmented: {augmented_example['text']}")

X = bert_combined_df["text"]
y = bert_combined_df["Organ"]


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")

char_vectorizer_bert_aug = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3,5),
    max_features=30000
)
X_train_tfidf = char_vectorizer_bert_aug.fit_transform(X_train)
X_test_tfidf = char_vectorizer_bert_aug.transform(X_test)

print(f"X_train_tfidf shape: {X_train_tfidf.shape}")
print(f"X_test_tfidf shape: {X_test_tfidf.shape}")

from sklearn.linear_model import LogisticRegression

model_bert_aug = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    C=3.0
)
model_bert_aug.fit(X_train_tfidf, y_train)

print("Model training with BERT augmented data complete.")

preds_bert_aug = model_bert_aug.predict(X_test_tfidf)

print("Accuracy (BERT Augmented):", accuracy_score(y_test, preds_bert_aug))
print("\nClassification Report (BERT Augmented):\n", classification_report(y_test, preds_bert_aug))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

cm_bert_aug = confusion_matrix(y_test, preds_bert_aug)

plt.figure(figsize=(10,8))
sns.heatmap(cm_bert_aug, annot=True, fmt="d", cmap="Blues", cbar=False)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix (BERT Augmented Data)')
plt.show()

text_for_prediction = "tansiyonum çıktı"
cleaned_text_for_prediction = temizle(text_for_prediction)

vec_for_prediction = char_vectorizer_bert_aug.transform([cleaned_text_for_prediction])
prediction_bert_aug = model_bert_aug.predict(vec_for_prediction)

print(f"Input Text: '{text_for_prediction}'")
print(f"Predicted Organ (BERT Augmented Model): {prediction_bert_aug[0]}")